apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dagster-exporter.fullname" . }}
  labels:
    {{- include "dagster-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if eq .Values.recreate_on_start true }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      {{- include "dagster-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dagster-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "dagster-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "dagster-exporter.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          livenessProbe:
            httpGet:
              path: /info
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
